[package]
name = "hubikoukku"
version = "0.1.0"
authors = ["Jaakko Pallari <jkpl@lepovirta.org>"]

[dependencies]
hyper = "0.7.2"
rust-ini = "0.9.2"
serde_json = "0.6.0"
log = "0.3"
env_logger = "0.3"
rust-crypto = "0.2.34"
